[package]
name = "tetris"
version = "0.1.0"
authors = ["sfadiga <sandro.fadiga@embraer.net.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm="*"
rand = "*"